import type { Assignment, Technician } from "./types.js";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 60 * 60 * 1000).toISOString();
const hoursFromNow = (h: number) => new Date(now + h * 60 * 60 * 1000).toISOString();
const plusMinutes = (iso: string, mins: number) => new Date(new Date(iso).getTime() + mins * 60 * 1000).toISOString();

function assignmentWindow(startInHours: number, durationMinutes: number) {
  const estimatedStartDateTime = hoursFromNow(startInHours);
  const estimatedEndDateTime = plusMinutes(estimatedStartDateTime, durationMinutes);
  return { estimatedStartDateTime, estimatedEndDateTime };
}

// TODO(template): Replace these mock assignments with records from your Field Service backend.
const assignmentSeed: Omit<Assignment, "estimatedTechnicianArrivalDateTime" | "assignedTechnicianId">[] = [
  {
    id: "HYD-A-1001",
    site: "Mindspace Campus Tower A",
    category: "HVAC",
    priority: "High",
    slaDue: hoursFromNow(2),
    ...assignmentWindow(1, 120),
    description: "Cooling not reaching target setpoint on 14th floor AHU cluster.",
    requiredSkills: ["HVAC", "AHU Maintenance"],
    customerName: "Arjun Reddy",
    customerPhone: "+91-90000-10001",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=11",
    assetId: "AHU-14A",
    estimatedDurationMinutes: 120,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-1/320/180",
    tags: ["SLA-Risk", "Enterprise", "Cooling"],
    location: { lat: 17.4483, lng: 78.3915, address: "Mindspace, HITEC City, Hyderabad" },
    status: "New",
    createdAt: hoursAgo(2),
    region: "Hyderabad",
    team: "Falcons"
  },
  {
    id: "HYD-A-1002",
    site: "Financial District Data Hub",
    category: "Network",
    priority: "Medium",
    slaDue: hoursFromNow(5),
    ...assignmentWindow(2, 90),
    description: "Edge switch uplink flapping in pod C rack lane.",
    requiredSkills: ["Network", "Switch Configuration"],
    customerName: "Niharika Rao",
    customerPhone: "+91-90000-10002",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=12",
    assetId: "SW-PODC-22",
    estimatedDurationMinutes: 90,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-2/320/180",
    tags: ["Connectivity", "Pod-C"],
    location: { lat: 17.4126, lng: 78.3488, address: "Nanakramguda, Financial District, Hyderabad" },
    status: "New",
    createdAt: hoursAgo(4),
    region: "Hyderabad",
    team: "Falcons"
  },
  {
    id: "HYD-A-1003",
    site: "Inorbit Mall Service Wing",
    category: "Electrical",
    priority: "High",
    slaDue: hoursFromNow(3),
    ...assignmentWindow(1.5, 150),
    description: "Main LT panel intermittent trip alarms during peak load.",
    requiredSkills: ["Electrical", "LT Panel Diagnostics"],
    customerName: "Sana Fatima",
    customerPhone: "+91-90000-10003",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=13",
    assetId: "LT-PANEL-B2",
    estimatedDurationMinutes: 150,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-3/320/180",
    tags: ["Critical", "Power"],
    location: { lat: 17.4338, lng: 78.3866, address: "Madhapur, Hyderabad" },
    status: "New",
    createdAt: hoursAgo(6),
    region: "Hyderabad",
    team: "Lions"
  },
  {
    id: "HYD-A-1004",
    site: "Raidurg Metro Station",
    category: "Escalator",
    priority: "Low",
    slaDue: hoursFromNow(11),
    ...assignmentWindow(6, 80),
    description: "Escalator vibration at landing point, periodic noise.",
    requiredSkills: ["Escalator", "Mechanical Inspection"],
    customerName: "Rahul Verma",
    customerPhone: "+91-90000-10004",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=14",
    assetId: "ESC-RD-02",
    estimatedDurationMinutes: 80,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-4/320/180",
    tags: ["Transit", "Routine"],
    location: { lat: 17.4309, lng: 78.3867, address: "Raidurg, Hyderabad" },
    status: "New",
    createdAt: hoursAgo(10),
    region: "Hyderabad",
    team: "Lions"
  },
  {
    id: "HYD-A-1005",
    site: "Banjara Hills Hospital Annex",
    category: "Medical Gas",
    priority: "High",
    slaDue: hoursFromNow(4),
    ...assignmentWindow(2, 140),
    description: "Low pressure alarm in oxygen manifold backup line.",
    requiredSkills: ["Medical Gas Systems", "Pressure Regulation"],
    customerName: "Dr. Ishita Menon",
    customerPhone: "+91-90000-10005",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=15",
    assetId: "MED-GAS-11",
    estimatedDurationMinutes: 140,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-5/320/180",
    tags: ["Healthcare", "Urgent"],
    location: { lat: 17.4156, lng: 78.4347, address: "Road No. 12, Banjara Hills" },
    status: "New",
    createdAt: hoursAgo(1),
    region: "Hyderabad",
    team: "Falcons"
  },
  {
    id: "HYD-A-1006",
    site: "Secunderabad Rail Logistics",
    category: "Generator",
    priority: "Medium",
    slaDue: hoursFromNow(7),
    ...assignmentWindow(3, 110),
    description: "Auto-start failure on backup DG set in bay 3.",
    requiredSkills: ["Generator", "DG Set Repair"],
    customerName: "Harsha Kulkarni",
    customerPhone: "+91-90000-10006",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=16",
    assetId: "DG-BAY3",
    estimatedDurationMinutes: 110,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-6/320/180",
    tags: ["Backup", "Logistics"],
    location: { lat: 17.4399, lng: 78.4983, address: "Secunderabad Yard, Hyderabad" },
    status: "New",
    createdAt: hoursAgo(7),
    region: "Hyderabad",
    team: "Lions"
  },
  {
    id: "HYD-A-1007",
    site: "Gachibowli Sports Arena",
    category: "Lighting",
    priority: "Low",
    slaDue: hoursFromNow(12),
    ...assignmentWindow(7, 75),
    description: "Floodlight cluster 4 not responding to scene control.",
    requiredSkills: ["Lighting", "Scene Control"],
    customerName: "Karthik Anand",
    customerPhone: "+91-90000-10007",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=17",
    assetId: "FL-CL4",
    estimatedDurationMinutes: 75,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-7/320/180",
    tags: ["Sports", "Lighting"],
    location: { lat: 17.4474, lng: 78.352, address: "Gachibowli Stadium Road" },
    status: "New",
    createdAt: hoursAgo(9),
    region: "Hyderabad",
    team: "Eagles"
  },
  {
    id: "HYD-A-1008",
    site: "Kondapur Residential Tower",
    category: "Plumbing",
    priority: "Medium",
    slaDue: hoursFromNow(6),
    ...assignmentWindow(2.5, 95),
    description: "Booster pump room leak and pressure drop complaints.",
    requiredSkills: ["Plumbing", "Pump Systems"],
    customerName: "Divya Ghosh",
    customerPhone: "+91-90000-10008",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=18",
    assetId: "BP-ROOM-2",
    estimatedDurationMinutes: 95,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-8/320/180",
    tags: ["Residential", "Water"],
    location: { lat: 17.4668, lng: 78.3636, address: "Kondapur Main Road" },
    status: "New",
    createdAt: hoursAgo(3),
    region: "Hyderabad",
    team: "Eagles"
  },
  {
    id: "HYD-A-1009",
    site: "Uppal Manufacturing Unit",
    category: "Conveyor",
    priority: "High",
    slaDue: hoursFromNow(2),
    ...assignmentWindow(1, 130),
    description: "Conveyor lane 2 jam alarms and motor overcurrent events.",
    requiredSkills: ["Conveyor Systems", "Motor Diagnostics"],
    customerName: "Mahesh Chandra",
    customerPhone: "+91-90000-10009",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=19",
    assetId: "CV-L2-MTR",
    estimatedDurationMinutes: 130,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-9/320/180",
    tags: ["Factory", "SLA-Risk"],
    location: { lat: 17.4058, lng: 78.5591, address: "Uppal Industrial Cluster" },
    status: "New",
    createdAt: hoursAgo(2),
    region: "Hyderabad",
    team: "Falcons"
  },
  {
    id: "HYD-A-1010",
    site: "Begumpet Corporate Plaza",
    category: "BMS",
    priority: "Medium",
    slaDue: hoursFromNow(8),
    ...assignmentWindow(4, 100),
    description: "Building management alarms not syncing to NOC dashboard.",
    requiredSkills: ["BMS", "System Integration"],
    customerName: "Meera Narayanan",
    customerPhone: "+91-90000-10010",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=20",
    assetId: "BMS-GW-01",
    estimatedDurationMinutes: 100,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-10/320/180",
    tags: ["Smart-Building", "Integration"],
    location: { lat: 17.4435, lng: 78.4626, address: "Begumpet Main Road" },
    status: "New",
    createdAt: hoursAgo(12),
    region: "Hyderabad",
    team: "Lions"
  },
  {
    id: "HYD-A-1011",
    site: "Kukatpally Retail Mega Store",
    category: "Refrigeration",
    priority: "High",
    slaDue: hoursFromNow(3),
    ...assignmentWindow(1.5, 125),
    description: "Walk-in chiller temperature drifting beyond compliance limits.",
    requiredSkills: ["Refrigeration", "Cold Chain Compliance"],
    customerName: "Ritika Sharma",
    customerPhone: "+91-90000-10011",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=21",
    assetId: "CHILLER-W2",
    estimatedDurationMinutes: 125,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-11/320/180",
    tags: ["Retail", "Cold-Chain"],
    location: { lat: 17.4948, lng: 78.3996, address: "KPHB Colony, Hyderabad" },
    status: "New",
    createdAt: hoursAgo(5),
    region: "Hyderabad",
    team: "Falcons"
  },
  {
    id: "HYD-A-1012",
    site: "Shamshabad Cargo Terminal",
    category: "Security",
    priority: "Low",
    slaDue: hoursFromNow(15),
    ...assignmentWindow(8, 70),
    description: "Two camera streams in loading bay are intermittently unavailable.",
    requiredSkills: ["CCTV", "Network Troubleshooting"],
    customerName: "Waseem Akhtar",
    customerPhone: "+91-90000-10012",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=22",
    assetId: "CCTV-LB-07",
    estimatedDurationMinutes: 70,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-12/320/180",
    tags: ["Aviation", "Surveillance"],
    location: { lat: 17.2403, lng: 78.4294, address: "Airport Cargo Zone, Hyderabad" },
    status: "New",
    createdAt: hoursAgo(14),
    region: "Hyderabad",
    team: "Eagles"
  },
  {
    id: "HYD-A-1013",
    site: "Jubilee Hills Media House",
    category: "UPS",
    priority: "Medium",
    slaDue: hoursFromNow(9),
    ...assignmentWindow(5, 85),
    description: "UPS battery bank health degraded warning in studio floor.",
    requiredSkills: ["UPS", "Battery Systems"],
    customerName: "Neha Kapoor",
    customerPhone: "+91-90000-10013",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=23",
    assetId: "UPS-ST-3",
    estimatedDurationMinutes: 85,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-13/320/180",
    tags: ["Broadcast", "Power"],
    location: { lat: 17.4239, lng: 78.4108, address: "Jubilee Hills Check Post" },
    status: "New",
    createdAt: hoursAgo(4),
    region: "Hyderabad",
    team: "Falcons"
  },
  {
    id: "HYD-A-1014",
    site: "Miyapur Metro Depot",
    category: "Fire Safety",
    priority: "High",
    slaDue: hoursFromNow(4),
    ...assignmentWindow(2.5, 115),
    description: "False positives from smoke detector loop in depot admin wing.",
    requiredSkills: ["Fire Safety", "Smoke Detection Systems"],
    customerName: "Vikram Sethi",
    customerPhone: "+91-90000-10014",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=24",
    assetId: "FAS-LOOP-9",
    estimatedDurationMinutes: 115,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-14/320/180",
    tags: ["Transit", "Compliance"],
    location: { lat: 17.4964, lng: 78.358, address: "Miyapur Depot, Hyderabad" },
    status: "New",
    createdAt: hoursAgo(11),
    region: "Hyderabad",
    team: "Lions"
  },
  {
    id: "HYD-A-1015",
    site: "LB Nagar Civic Complex",
    category: "Elevator",
    priority: "Low",
    slaDue: hoursFromNow(18),
    ...assignmentWindow(10, 90),
    description: "Elevator door alignment drift and occasional door reopen events.",
    requiredSkills: ["Elevator", "Door Mechanism"],
    customerName: "Anita Joseph",
    customerPhone: "+91-90000-10015",
    customerProfilePicUrl: "https://i.pravatar.cc/160?img=25",
    assetId: "LIFT-BLK-C",
    estimatedDurationMinutes: 90,
    siteImageUrl: "https://picsum.photos/seed/hyd-site-15/320/180",
    tags: ["Public-Sector", "Routine"],
    location: { lat: 17.3458, lng: 78.5522, address: "LB Nagar Main Junction" },
    status: "New",
    createdAt: hoursAgo(13),
    region: "Hyderabad",
    team: "Eagles"
  }
];

export const assignments: Assignment[] = assignmentSeed.map((assignment) => ({
  ...assignment,
  estimatedTechnicianArrivalDateTime: null,
  assignedTechnicianId: null
}));

// TODO(template): Replace these mock technicians with real availability + live location feed.
export const technicians: Technician[] = [
  {
    id: "HYD-T-201",
    name: "Rohit Varma",
    profilePicUrl: "https://i.pravatar.cc/160?img=41",
    phone: "+91-91000-20001",
    rating: 4.7,
    yearsExperience: 8,
    shift: "Morning",
    vehicleType: "Van",
    skills: ["HVAC", "Electrical"],
    certifications: ["HVAC Level-2", "Electrical Safety"],
    languages: ["English", "Telugu", "Hindi"],
    location: { lat: 17.4562, lng: 78.4045, address: "Madhapur" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-202",
    name: "Ayesha Khan",
    profilePicUrl: "https://i.pravatar.cc/160?img=42",
    phone: "+91-91000-20002",
    rating: 4.8,
    yearsExperience: 6,
    shift: "Evening",
    vehicleType: "Car",
    skills: ["Network", "Fiber", "CCTV"],
    certifications: ["CCNA", "Fiber Splicing"],
    languages: ["English", "Urdu", "Hindi"],
    location: { lat: 17.4285, lng: 78.3372, address: "Financial District" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-203",
    name: "Kiran Choudhary",
    profilePicUrl: "https://i.pravatar.cc/160?img=43",
    phone: "+91-91000-20003",
    rating: 4.6,
    yearsExperience: 10,
    shift: "Morning",
    vehicleType: "Bike",
    skills: ["Mechanical", "Controls", "Elevator"],
    certifications: ["Lift Systems", "Industrial Controls"],
    languages: ["English", "Telugu"],
    location: { lat: 17.4219, lng: 78.3725, address: "HITEC City" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-204",
    name: "Navya Iyer",
    profilePicUrl: "https://i.pravatar.cc/160?img=44",
    phone: "+91-91000-20004",
    rating: 4.9,
    yearsExperience: 7,
    shift: "Night",
    vehicleType: "Van",
    skills: ["UPS", "Electrical", "Generator"],
    certifications: ["UPS Specialist", "DG Operations"],
    languages: ["English", "Tamil", "Hindi"],
    location: { lat: 17.4398, lng: 78.4985, address: "Secunderabad" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-205",
    name: "Pranav Reddy",
    profilePicUrl: "https://i.pravatar.cc/160?img=45",
    phone: "+91-91000-20005",
    rating: 4.5,
    yearsExperience: 5,
    shift: "Morning",
    vehicleType: "Bike",
    skills: ["Plumbing", "Piping"],
    certifications: ["Industrial Plumbing"],
    languages: ["English", "Telugu"],
    location: { lat: 17.4668, lng: 78.3634, address: "Kondapur" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-206",
    name: "Sowmya N",
    profilePicUrl: "https://i.pravatar.cc/160?img=46",
    phone: "+91-91000-20006",
    rating: 4.8,
    yearsExperience: 9,
    shift: "Evening",
    vehicleType: "Car",
    skills: ["Fire Safety", "Controls", "Safety"],
    certifications: ["FAS Commissioning", "Safety Lead"],
    languages: ["English", "Kannada", "Hindi"],
    location: { lat: 17.4965, lng: 78.3582, address: "Miyapur" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-207",
    name: "Vivek Gupta",
    profilePicUrl: "https://i.pravatar.cc/160?img=47",
    phone: "+91-91000-20007",
    rating: 4.3,
    yearsExperience: 4,
    shift: "Morning",
    vehicleType: "Bike",
    skills: ["CCTV", "Network"],
    certifications: ["Surveillance Systems"],
    languages: ["English", "Hindi"],
    location: { lat: 17.2411, lng: 78.4301, address: "Shamshabad" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-208",
    name: "Shruti Patel",
    profilePicUrl: "https://i.pravatar.cc/160?img=48",
    phone: "+91-91000-20008",
    rating: 4.9,
    yearsExperience: 11,
    shift: "Night",
    vehicleType: "Van",
    skills: ["Medical Gas", "Safety", "Piping"],
    certifications: ["Medical Systems", "Safety Inspector"],
    languages: ["English", "Gujarati", "Hindi"],
    location: { lat: 17.4158, lng: 78.435, address: "Banjara Hills" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-209",
    name: "Srikar D",
    profilePicUrl: "https://i.pravatar.cc/160?img=49",
    phone: "+91-91000-20009",
    rating: 4.4,
    yearsExperience: 6,
    shift: "Evening",
    vehicleType: "Car",
    skills: ["Refrigeration", "HVAC"],
    certifications: ["Cold Chain Systems"],
    languages: ["English", "Telugu"],
    location: { lat: 17.495, lng: 78.3998, address: "Kukatpally" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-210",
    name: "Anmol Singh",
    profilePicUrl: "https://i.pravatar.cc/160?img=50",
    phone: "+91-91000-20010",
    rating: 4.2,
    yearsExperience: 3,
    shift: "Morning",
    vehicleType: "Bike",
    skills: ["Electrical", "Lighting"],
    certifications: ["Wiring Specialist"],
    languages: ["English", "Hindi", "Punjabi"],
    location: { lat: 17.4472, lng: 78.3523, address: "Gachibowli" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-211",
    name: "Lavanya K",
    profilePicUrl: "https://i.pravatar.cc/160?img=51",
    phone: "+91-91000-20011",
    rating: 4.6,
    yearsExperience: 8,
    shift: "Night",
    vehicleType: "Van",
    skills: ["BMS", "Network", "Controls"],
    certifications: ["BMS Integrator"],
    languages: ["English", "Telugu", "Hindi"],
    location: { lat: 17.4433, lng: 78.4624, address: "Begumpet" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-212",
    name: "Nitin Joshi",
    profilePicUrl: "https://i.pravatar.cc/160?img=52",
    phone: "+91-91000-20012",
    rating: 4.5,
    yearsExperience: 7,
    shift: "Evening",
    vehicleType: "Car",
    skills: ["Mechanical", "Escalator", "Elevator"],
    certifications: ["Vertical Transport"],
    languages: ["English", "Hindi"],
    location: { lat: 17.4188, lng: 78.4012, address: "Raidurg" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-213",
    name: "Pooja Arora",
    profilePicUrl: "https://i.pravatar.cc/160?img=53",
    phone: "+91-91000-20013",
    rating: 4.8,
    yearsExperience: 9,
    shift: "Morning",
    vehicleType: "Van",
    skills: ["Electrical", "UPS", "Safety"],
    certifications: ["Electrical Audit"],
    languages: ["English", "Hindi"],
    location: { lat: 17.4241, lng: 78.4106, address: "Jubilee Hills" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-214",
    name: "Tarun Bhat",
    profilePicUrl: "https://i.pravatar.cc/160?img=54",
    phone: "+91-91000-20014",
    rating: 4.1,
    yearsExperience: 4,
    shift: "Night",
    vehicleType: "Bike",
    skills: ["Plumbing", "General"],
    certifications: ["Facility Operations"],
    languages: ["English", "Hindi"],
    location: { lat: 17.3574, lng: 78.5668, address: "LB Nagar" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-215",
    name: "Keerthi P",
    profilePicUrl: "https://i.pravatar.cc/160?img=55",
    phone: "+91-91000-20015",
    rating: 4.7,
    yearsExperience: 6,
    shift: "Morning",
    vehicleType: "Car",
    skills: ["Generator", "Electrical"],
    certifications: ["DG Specialist"],
    languages: ["English", "Telugu"],
    location: { lat: 17.406, lng: 78.5592, address: "Uppal" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-216",
    name: "Harini S",
    profilePicUrl: "https://i.pravatar.cc/160?img=56",
    phone: "+91-91000-20016",
    rating: 4.9,
    yearsExperience: 12,
    shift: "Evening",
    vehicleType: "Van",
    skills: ["Safety", "Fire Safety", "Electrical"],
    certifications: ["Chief Safety Officer"],
    languages: ["English", "Telugu", "Tamil"],
    location: { lat: 17.4011, lng: 78.3354, address: "Nanakramguda" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-217",
    name: "Yashwant M",
    profilePicUrl: "https://i.pravatar.cc/160?img=57",
    phone: "+91-91000-20017",
    rating: 4.3,
    yearsExperience: 5,
    shift: "Night",
    vehicleType: "Bike",
    skills: ["Mechanical", "Conveyor", "Hydraulics"],
    certifications: ["Plant Maintenance"],
    languages: ["English", "Telugu"],
    location: { lat: 17.4397, lng: 78.4982, address: "Secunderabad" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-218",
    name: "Farah Ali",
    profilePicUrl: "https://i.pravatar.cc/160?img=58",
    phone: "+91-91000-20018",
    rating: 4.6,
    yearsExperience: 7,
    shift: "Morning",
    vehicleType: "Car",
    skills: ["Network", "BMS", "CCTV"],
    certifications: ["Network Ops"],
    languages: ["English", "Urdu", "Hindi"],
    location: { lat: 17.4437, lng: 78.3918, address: "Madhapur" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-219",
    name: "Dinesh Kumar",
    profilePicUrl: "https://i.pravatar.cc/160?img=59",
    phone: "+91-91000-20019",
    rating: 4.4,
    yearsExperience: 6,
    shift: "Evening",
    vehicleType: "Van",
    skills: ["HVAC", "Refrigeration", "Electrical"],
    certifications: ["HVAC Advanced"],
    languages: ["English", "Hindi", "Telugu"],
    location: { lat: 17.4947, lng: 78.3994, address: "Kukatpally" },
    available: true,
    region: "Hyderabad"
  },
  {
    id: "HYD-T-220",
    name: "Shalini R",
    profilePicUrl: "https://i.pravatar.cc/160?img=60",
    phone: "+91-91000-20020",
    rating: 4.8,
    yearsExperience: 10,
    shift: "Morning",
    vehicleType: "Car",
    skills: ["Electrical", "Controls", "UPS"],
    certifications: ["Energy Systems", "Control Panels"],
    languages: ["English", "Telugu", "Hindi"],
    location: { lat: 17.4667, lng: 78.3639, address: "Kondapur" },
    available: true,
    region: "Hyderabad"
  }
];
